// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)


document.addEventListener('DOMContentLoaded', function(){
  Typed.new('.type', {
    strings: ["neighbor", "family", "team", "community"],
    stringsElement: null,
// typing speed
typeSpeed: 60,
// time before typing starts
startDelay: 600,
// backspacing speed
backSpeed: 20,
// time before backspacing
backDelay: 500,
// loop
loop: true,
// false = infinite
loopCount: 5,
// show cursor
showCursor: false,
// character for cursor
cursorChar: "|",
// attribute to type (null == text)
attr: null,
// either html or text
contentType: 'html',
  });
});
